version: '3'
services:
    db:
        image: qdb/h2:latest
        container_name: db
        ports:
            - 1521:1521
    cms:
        image: qdb-cms:1.0.0-SNAPSHOT
        ports:
            - 9080:8080
        environment:
            spring_profiles_active: prod
        depends_on:
           - db
    document:
        image: qdb-document-upload:1.0.0-SNAPSHOT
        ports:
            - 9081:8080
        environment:
            spring_profiles_active: prod
        depends_on:
            - db
